spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  profiles:
#    active: prod
  config:
    activate:
      on-profile:
        - prod
  application:
    name: py
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/py?serverTimezone=GMT%2B8
    username: root
    password: pwb2001
  #  session 失效时间
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 86400
    store-type: REDIS
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /py

mybatis-plus:
  mapper-locations: classpath:com/user/py/mapper/xml/*.xml
  #    日志
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tN1Ga2AehUD3HWyprsx
      keysecret: QpK6KNMFoZdS8koHCDu5zvGc1ZTojN
      bucketname: bing-edu
email:
  fromEmail: verification_ice@qq.com
  password: yfjebidgptbpecff